#!/bin/sh

# Definizione variabili
MONITOR_SCRIPT="/etc/init.d/monitor"
POSTFIX_SCRIPT="/etc/init.d/postfix-fix"
DNS_SCRIPT="/root/99-update-and-notify-dns"
HOTPLUG_DHCP_LINK="/etc/hotplug.d/dhcp/99-update-and-notify-dns"
HOTPLUG_IFACE_LINK="/etc/hotplug.d/iface/99-update-ddns"
NAMED_SCRIPT="/etc/init.d/named"
DDNS_SCRIPT="/root/99-update-ddns"
SYSTEMINFO_SCRIPT="/root/systemInfoJson.sh"

# Monitor
if [ -f "$MONITOR_SCRIPT" ]; then
    chmod +x "$MONITOR_SCRIPT"
    "$MONITOR_SCRIPT" enable
fi

# Postfix fix
if [ -f "$POSTFIX_SCRIPT" ]; then
    chmod +x "$POSTFIX_SCRIPT"
    "$POSTFIX_SCRIPT" enable
fi

# DNS hotplug
if [ -f "$DNS_SCRIPT" ]; then
    chmod +x "$DNS_SCRIPT"
    ln -sf "$DNS_SCRIPT" "$HOTPLUG_DHCP_LINK"
fi

# DDNS hotplug
if [ -f "$DDNS_SCRIPT" ]; then
    chmod +x "$DDNS_SCRIPT"
    ln -sf "$DDNS_SCRIPT" "$HOTPLUG_IFACE_LINK"
fi

# Named (fix)
# Faccio il backup dello script di avvio originale e lo sostiuisco col mio personalizzato
if [ -f "$NAMED_SCRIPT.pg" ]; then
    # Controlla se il file destinazione esiste già
    if [ -f "$NAMED_SCRIPT" ]; then
        # Esegui la logica solo se i file sono diversi
        if ! diff -q "$NAMED_SCRIPT.pg" "$NAMED_SCRIPT" > /dev/null; then
            mv "$NAMED_SCRIPT" "$NAMED_SCRIPT.orig"
            mv "$NAMED_SCRIPT.pg" "$NAMED_SCRIPT"
            chmod 755 "$NAMED_SCRIPT"
        else
            # Opzionale: rimuovi il file .pg se è identico per pulizia
            rm "$NAMED_SCRIPT.pg"
        fi
    else
        # Se il file originale non esiste, sposta semplicemente il nuovo
        mv "$NAMED_SCRIPT.pg" "$NAMED_SCRIPT"
        chmod 755 "$NAMED_SCRIPT"
    fi
fi

# DDNS hotplug
if [ -f "$SYSTEMINFO_SCRIPT" ]; then
    chmod +x "$SYSTEMINFO_SCRIPT"
    ln -sf "$SYSTEMINFO_SCRIPT" "/www/cgi-bin/systemInfoJson.sh"
fi

exit 0
