#!/bin/sh
# Script eseguito una sola volta al primo boot

# --- 1) Creazione utente e gruppo ---
if ! getent group adguardhome >/dev/null 2>&1; then
    addgroup adguardhome
fi

if ! id adguardhome >/dev/null 2>&1; then
    adduser -D -G adguardhome adguardhome
fi

exit 0
