#!/bin/sh

if [ -x /etc/init.d/monitor ]; then
    /etc/init.d/monitor enable
    /etc/init.d/monitor start
fi

if [ -x /etc/init.d/postfix-fix ]; then
    /etc/init.d/postfix-fix enable
    /etc/init.d/postfix-fix start
fi

exit 0
