name: OpenWrt MT6000 SNAPSHOT GO

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Questo è solo un segnaposto per abilitare il menu."
